Develop
Olkerty/mesto-project pull request #12
Opened 2021-10-07 19:34 UTC by Olkerty

2021-10-08 15:28 UTC, AygulMalikova commented
Отличная работа! 

У вас хорошо структурированный и чистый код, весь необходимый функционал реализован!

Но есть небольшие замечания. В первую очередь прошу вас обратить внимание на файловую структуру проекта. Пожалуйста, исправьте, чтобы у вас не было дублирования кода. И также, были оставлены другие комментарии и рекомендации по улучшению вашего кода.

Я напоминаю, что работа будет принята, как только все критические ошибки будут исправлены. Желаю вам удачи!

2021-10-09 19:02 UTC, AygulMalikova requested changes

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/api.js
> +	getResponseData(data) {
Можно лучше:

Здорово, что вы вынесли проверку ответа сервера и преобразование из json в отдельный метод и переиспользуете его в остальных методах класса Api. Однако он используется только в этом классе, поэтому его можно сделать приватным

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/api.js
> +		this._urlAvatar = urlAvatar;
Надо исправить:

Вместо того, чтобы в конструктор класса передавать несколько переменных с одинаковым префиксом, вам следует передать только одну переменную `https://nomoreparties.co/v1/plus-cohort-1/` и в методах класса апи добавлять уже необходимые пути (например, `users/me`, `users/me/avatar` и т.д.). Не забудьте также его использовать в методах toggleLikeAtServer и deletePhotoGridElementFromServer

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/cards.js
> +export class Card {
Надо исправить:

Было бы лучше называть файлы в соответствии с классами внутри них. Например, Card.js, Popup.js и т.д.

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/cards.js
> +		const pictureOnCard = new PopUpWithImage(`div[name="popupform__picture"]`);
Надо исправить:

Модальное окно с картинкой на странице всегда одно - меняется только его контент (картинка и надпись). Т.е. экземпляр класса `PopupWithImage` достаточно создавать только один раз, а не для каждой карточки. Следовательно, при открытии следует менять его содержимое.

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/cards.js
> +﻿import { api } from "./script.js";
Надо исправить:
Если вам необходимо использовать экземпляр класса, то его следует передать в конструктор класса Card. 

Можно лучше:
Однако было бы лучше передавать хендлеры (на лайк, удаление) в конструктор вместо экземпляра класса api для слабой связанности между классами

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/modal.js
> +		this.setEventListeners();
Надо исправить:

Вызов функции `setEventListeners` должен происходить только один раз, а не при каждом открытии модального окна. Пожалуйста, перенесите вызов этой функции для каждого попапа в index.js в глобальный скоуп

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/modal.js
> +		if (event.key == 'Escape') {
Можно лучше:

Для сравнения следует использовать тройное ровно (или !==) https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/%D0%9E%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D1%8B_%D1%81%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/modal.js
> +		document.addEventListener('mouseup', this.closeOverlay);
Надо исправить:

Обработчик на закрытие с помощью ESC должен добавляться при открытии и удаляться при закрытии. Внутри функции `setEventListeners` необходимо оставить только добавление слушателей на оверлей и крестик. При закрытии их не нужно удалять, т.к. они устанавливаются только один раз

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/modal.js
> +export class PopUpWithImage extends Popup {
Надо исправить:

Каждый класс модального окна следует вынести в отдельные файлы

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/modal.js
> +		this._popup.querySelector(".popupform__image").alt = name;
Можно лучше:

Поиск данных DOM элементов необходимо объявить в конструкторе класса, чтобы каждый раз при открытии попапа не выполнялся их поиск.

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/modal.js
> +		this._callBack = callBack;
Надо исправить:

`callBack` - не самое подходящее название. Вам следует переименовать его на более явное, например, handleSubmit

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/modal.js
> +		this._popup.classList.add("popupform_opened");
Надо исправить:

Вместо того, чтобы дублировать код открытия модального окна, вам следует вызывать родительский метод с помощью super

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/UserInfo.js
> +import {api} from "./script.js";
Надо исправить:
Если вам необходимо использовать экземпляр класса, то его следует передать в конструктор класса UserInfo.

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/script.js
> +  userInfo.getUserInfo(),
Отлично:

Здорово, что для запроса изначальных данных вы используете Promise.all!

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/script.js
>    .then((values) => {
Можно лучше:

Вам следует деструктуризировать массив, чтобы далее не обращаться к его элементам по индексу https://learn.javascript.ru/destructuring

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/script.js
> +    const initialCardSection = new Section({
Надо исправить:

Вам следует переиспользовать экземпляр класса Section при начальном отображении карточек и для создания новых. Нет необходимости создавать два отдельных объекта.

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/script.js
> +        const card = new Card(item, isLiked, cardIsMine);
Надо исправить:

Функционал, отвечающий за создание карточки, дублируется в двух местах. Вам следует вынести его в отдельную функцию

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/script.js
> +      addPopup._popup.querySelector('.popupform__form-itself').reset();
Надо исправить:

Вы не можете обращаться к приватным полям извне

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/script.js
> +  editProfileForm.saveButton.classList.add('popupform__save-button_inactive');
Надо исправить:

Как вы можете заметить, код, отвечающий за сброс кнопки сохранения, частично совпадает с функцией `_toggleButtonState` внутри класса валидации. Вам следует вынести общий код в отдельный метод и разместить внутри класса валидации, сделать его публичным (чтобы можно было обращаться из script.js) и вызывать отсюда и из метода `_toggleButtonState` .

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/script.js
> +profileHoverMask.addEventListener('click', () => {
Надо исправить:

Очень важно иметь правильно отформатированный код для улучшения его читабельности. Пожалуйста, обратитесь к данной статье для изучения стандартов https://learn.javascript.ru/coding-style

Если вы используете IDE (например, VS code), то вы можете автоматически форматировать ваш код:
 https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode

2021-10-09 19:02 UTC, AygulMalikova commented on src/scripts/modal.js
> +export class DeletePopup extends Popup {
Отлично:

Здорово, что вы реализовали модальное окно подтверждения удаления!

2021-10-11 18:07 UTC, ssklv3o commented on src/scripts/api.js
> +	getResponseData(data) {
Готово

2021-10-11 18:13 UTC, ssklv3o commented on src/scripts/api.js
> +		this._urlAvatar = urlAvatar;
Готово

2021-10-11 18:15 UTC, ssklv3o commented on src/scripts/cards.js
> +export class Card {
 Готово

2021-10-11 18:21 UTC, ssklv3o commented on src/scripts/cards.js
> +		const pictureOnCard = new PopUpWithImage(`div[name="popupform__picture"]`);
Готово

2021-10-11 18:24 UTC, ssklv3o commented on src/scripts/cards.js
> +﻿import { api } from "./script.js";
Готово

2021-10-11 18:40 UTC, ssklv3o commented on src/scripts/modal.js
> +		this.setEventListeners();
Готово

2021-10-11 18:40 UTC, ssklv3o commented on src/scripts/modal.js
> +		if (event.key == 'Escape') {
Готово

2021-10-11 18:42 UTC, ssklv3o commented on src/scripts/modal.js
> +		document.addEventListener('mouseup', this.closeOverlay);
Готово

2021-10-11 18:47 UTC, ssklv3o commented on src/scripts/modal.js
> +export class PopUpWithImage extends Popup {
Готовое

2021-10-11 18:53 UTC, ssklv3o commented on src/scripts/modal.js
> +		this._popup.querySelector(".popupform__image").alt = name;
готово

2021-10-11 18:54 UTC, ssklv3o commented on src/scripts/modal.js
> +		this._callBack = callBack;
Готово

2021-10-11 19:23 UTC, ssklv3o commented on src/scripts/script.js
> +  userInfo.getUserInfo(),
Готово

2021-10-11 19:23 UTC, ssklv3o commented on src/scripts/modal.js
> +export class DeletePopup extends Popup {
Готово

2021-10-11 19:34 UTC, ssklv3o commented on src/scripts/modal.js
> +		this._popup.classList.add("popupform_opened");
Готово

2021-10-11 19:37 UTC, ssklv3o commented on src/scripts/UserInfo.js
> +import {api} from "./script.js";
Готово

2021-10-11 19:39 UTC, ssklv3o commented on src/scripts/script.js
>    .then((values) => {
Готово

2021-10-11 19:47 UTC, ssklv3o commented on src/scripts/script.js
> +        const card = new Card(item, isLiked, cardIsMine);
Готово

2021-10-11 19:56 UTC, ssklv3o commented on src/scripts/script.js
> +    const initialCardSection = new Section({
Готово

2021-10-11 19:57 UTC, ssklv3o commented on src/scripts/script.js
> +      addPopup._popup.querySelector('.popupform__form-itself').reset();
Готово

2021-10-11 19:58 UTC, ssklv3o commented on src/scripts/script.js
> +profileHoverMask.addEventListener('click', () => {
Готово

2021-10-11 20:08 UTC, ssklv3o commented on src/scripts/script.js
> +  editProfileForm.saveButton.classList.add('popupform__save-button_inactive');
Готово

2021-10-11 20:16 UTC, closed without merging